"""initial_schema

Revision ID: 21f1c1209d8d
Revises: 
Create Date: 2026-06-13 20:42:48.088932


Created by the code: 
alembic revision --autogenerate -m "initial_schema"
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21f1c1209d8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('cost_percentage', sa.Float(), nullable=False),
    sa.Column('cost_fixed_paise', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_second', sa.Integer(), nullable=False),
    sa.Column('supported_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settlement_days', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_configs_name'), 'gateway_configs', ['name'], unique=True)
    op.create_table('gateway_health_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('p95_latency_ms', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker_state', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_health_metrics_gateway'), 'gateway_health_metrics', ['gateway'], unique=False)
    op.create_index(op.f('ix_gateway_health_metrics_recorded_at'), 'gateway_health_metrics', ['recorded_at'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('merchant_id', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('processed_webhook_events',
    sa.Column('gateway', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('gateway', 'event_id')
    )
    op.create_index(op.f('ix_processed_webhook_events_transaction_id'), 'processed_webhook_events', ['transaction_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_order_id', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ROUTE_SELECTED', 'ROUTE_FAILED', 'AUTH_INITIATED', 'AUTHORISED', 'AUTH_FAILED', 'AUTH_TIMEOUT', 'AUTH_EXPIRED', 'CAPTURE_INITIATED', 'CAPTURED', 'PARTIALLY_CAPTURED', 'CAPTURE_FAILED', 'VOID_INITIATED', 'VOIDED', 'REFUND_INITIATED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'REFUND_FAILED', 'SETTLED', 'DISPUTE_OPENED', 'DISPUTE_RESOLVED', 'FAILED', 'ABANDONED', name='transactionstatus'), nullable=False),
    sa.Column('gateway', sa.Enum('RAZORPAY', 'STRIPE', 'PAYU', 'UPI', name='gatewayname'), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('routing_score', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NETBANKING', 'WALLET', name='paymentmethod'), nullable=False),
    sa.Column('payment_method_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('gateway_error_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_transactions_gateway_payment_id'), 'transactions', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_order_id'), 'transactions', ['merchant_order_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_gateway'), 'webhook_events', ['gateway'], unique=False)
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gateway_refund_id', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_index(op.f('ix_refunds_transaction_id'), 'refunds', ['transaction_id'], unique=False)
    op.create_table('transaction_state_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('gateway_reference', sa.String(length=255), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_state_logs_created_at'), 'transaction_state_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_transaction_state_logs_transaction_id'), 'transaction_state_logs', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_state_logs_transaction_id'), table_name='transaction_state_logs')
    op.drop_index(op.f('ix_transaction_state_logs_created_at'), table_name='transaction_state_logs')
    op.drop_table('transaction_state_logs')
    op.drop_index(op.f('ix_refunds_transaction_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_gateway'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_gateway_payment_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_processed_webhook_events_transaction_id'), table_name='processed_webhook_events')
    op.drop_table('processed_webhook_events')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_gateway_health_metrics_recorded_at'), table_name='gateway_health_metrics')
    op.drop_index(op.f('ix_gateway_health_metrics_gateway'), table_name='gateway_health_metrics')
    op.drop_table('gateway_health_metrics')
    op.drop_index(op.f('ix_gateway_configs_name'), table_name='gateway_configs')
    op.drop_table('gateway_configs')
    # ### end Alembic commands ###
